Repository 30th-SOPKATHON-8/Sopkathon-Server, pull requests merged in 2022-05, with the labels that each got.

#3 Feature/#2
  src/interfaces/user/UserInfo.ts
  src/loaders/db.ts
  src/models/user.ts
Labels: 😈 소령

#4 [FEAT] Record Schema 정의
  src/interfaces/record/RecordInfo.ts
  src/models/Record.ts
Labels: 👍 enhancement, 🦋 영권

#7 Feature/#5
  src/config/index.ts
  src/controllers/RecordController.ts
  src/interfaces/record/GetTotalRecordDto.ts
  src/loaders/db.ts
  src/modules/responseMessage.ts
  src/routes/RecordRouter.ts
  src/routes/index.ts
  src/services/RecordService.ts
Labels: 😈 소령, ✨GET✨

#9 [GET] record 조회 API 구현
  package.json
  src/controllers/RecordController.ts
  src/controllers/UserController.ts
  src/controllers/index.ts
  src/interfaces/record/Rec.ts
  src/interfaces/record/RecordResponseDto.ts
  src/modules/categoryList.ts
  src/modules/convertToTwoDigits.ts
  src/modules/responseMessage.ts
  src/routes/RecordRouter.ts
  src/services/RecordService.ts
  src/services/index.ts
Labels: 👍 enhancement, 🦋 영권, ✨GET✨

#11 [REFACTOR] remove not used module and variable
  src/controllers/RecordController.ts
  src/index.ts
  src/loaders/db.ts
  src/modules/util.ts
Labels: 👍 enhancement, 🦋 영권

#12 Feature/#8
  src/controllers/RecordController.ts
  src/interfaces/record/PostRequestRecordDto.ts
  src/interfaces/record/PostResponseRecordDto.ts
  src/interfaces/record/index.ts
  src/routes/RecordRouter.ts
  src/services/RecordService.ts
Labels: 😈 소령, ✨POST✨

#14 [FIX] getRecords coin response
  src/services/RecordService.ts
Labels: 👍 enhancement, 🦋 영권

#15 fix: skip request argument when no used
  src/controllers/RecordController.ts
Labels: 😈 소령, ✨POST✨

#16 fix: 사용되지 않는 인자 진짜 해결
  src/controllers/RecordController.ts
Labels: 😈 소령, ✨POST✨

#20 [FIX] Date data parsing issue
  src/modules/convertDateFormat.ts
Labels: 🚨 bug, 👍 enhancement, 🦋 영권

#21 [Deploy] fix convertDateFormat function
  src/modules/convertDateFormat.ts
Labels: 🚨 bug, 👍 enhancement, 🦋 영권
